export const ROUTES = {
  LOGIN: "/login",
  ONBOARDING: "/onboarding",
  DASHBOARD: "/dashboard",
  GOVERNANCE: "/governance",
  MEMBERS: "/members",
  MEETINGS: "/meetings",
  MEETINGS_NEW: "/meetings/new",
  FINANCE: "/finance",
  BOARD: "/board",
  SETTINGS: "/settings",
  BILLING: "/billing",
  PROFILE: "/profile",
  DUES: "/dues",
  UNAUTHORIZED: "/unauthorized",
} as const
